#!/usr/bin/env bash
set -e
set -o xtrace

docker build -t eu.gcr.io/aidbox-next/zero-ci-test:0.0.1 .

docker login -u _json_key -p "$DOCKER_KEY" https://gcr.io

docker push eu.gcr.io/aidbox-next/zero-ci-test:0.0.1
