#!/usr/bin/env bash
set -e
set -o xtrace

mkdir /workspace

if [ -z "$DONT_PULL" ]; then
  ls /workspace/.git || git clone $REPO /workspace;
  cd /workspace;
  git pull;
else
  export KUBECONFIG=/root/.kube/config
fi

cd /workspace

exec "$@"